spring:
  threads.virtual.enabled: true
  datasource:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.batch_size: 5
  h2.console.enabled: true

jasypt.encryptor.password: ${JASYPT_PASSWORD}